# Generated by Django 3.2.15 on 2022-09-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
