# Generated by Django 3.2.15 on 2022-09-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_crypto_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='code',
        ),
    ]
