# Generated by Django 3.2.15 on 2022-09-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_crypto_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('onehour', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('oneday', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sevenday', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('marketcap', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('supply', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Crypto',
        ),
    ]
