# Generated by Django 3.2.15 on 2022-09-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220923_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocoin',
            name='marketcap',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocoin',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocoin',
            name='oneday',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocoin',
            name='onehour',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocoin',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocoin',
            name='sevenday',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocoin',
            name='supply',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocoin',
            name='volume',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
